export type LongitudinalLocale = 'en' | 'zh';
export const longitudinalCopy = {
  en: {
    workspace: {
      back: 'Research', title: 'Multi-round coevolution',
      lead: 'Two randomly assigned groups receive the same tasks and revision opportunities. In one group, reviewed method updates take effect in the next round; the other keeps the initial method throughout. Every round separates independent work, Agent help and independent transfer.',
      refresh: 'Refresh saved progress', list: 'Study list', studies: 'Frozen studies', none: 'No multi-round study yet. Prepare and freeze one below.',
      unavailable: 'Some study records could not be read. Their files were preserved.',
      prepare: 'Prepare a new study', open: 'Open',
      participants: 'participants', pending: 'awaiting review', active: 'in progress', complete: 'complete',
      rounds: 'rounds', updated: 'Updated',
      readiness: 'Before inviting anyone', modelReady: 'Fixed model', modelMissing: 'Configure a compatible model in AI settings first. New protocols freeze the current model, temperature and reply budget.',
      accessReady: 'Access protection is on: Web password and access token are configured.', accessMissing: 'Enable a Web password and an access token in Settings before creating participant links. Remote participation requires HTTPS.',
      settings: 'Open Settings', aiSettings: 'AI settings',
      error: 'Could not save or load. Your input is preserved. Check the configuration or refresh saved progress.',
      errors: { configuration: 'No compatible model is configured. Open AI settings and try again.', conflict: 'Saved state changed or the fixed model differs from your current settings. Refresh saved progress before continuing.', invalid: 'Some fields are missing or out of range. Check the list above the freeze button.', unavailable: 'Participant links need a Web password, an access token and HTTPS for remote use.', storage: 'The change was not confirmed. Retry the same action; nothing was duplicated.', 'not-found': 'This study is unavailable. Return to the study list.', unauthorized: 'Your session expired. Sign in again and reopen this page.', forbidden: 'Open this page from your MindOS instance.' },
    },
    form: {
      jump: 'Go to section', basics: 'Study', title: 'Study title', hypothesis: 'Hypothesis', hypothesisHint: 'State what would count against the idea, not only what you hope to see.',
      participantInfo: 'What participants read', consent: 'Consent information', withdrawal: 'Withdrawal and erasure information',
      method: 'Initial method (both groups)', methodHint: 'The exact text the Agent receives in the first round. Later rounds may use a reviewed revision in one group only.',
      runtime: 'Fixed model', runtimeSummary: (provider: string, model: string, temperature: number, tokens: number) => `${provider} / ${model} · temperature ${temperature} · ${tokens} tokens per reply including reasoning`,
      runtimeMissing: 'Configure a compatible model in Settings first.',
      schedule: 'Size and schedule', capacity: 'Maximum invitations', capacityHint: 'Storage limit, not a sample-size recommendation. Assignment is balanced in pairs.', delay: 'Hours between rounds', delayHint: 'Use 0 only for workflow checks. Real cross-day returns need at least 24.',
      rounds: 'Rounds', round: 'Round', before: 'Independent task before help', coaching: 'Assisted practice task', after: 'New independent transfer task', reference: 'Private scoring reference',
      referenceHint: 'Never shown to participants or sent to the model. Included in blind review packets.',
      updateAllowed: 'Offer a method revision after this round', finalRound: 'The final round has no later update.',
      addRound: 'Add round', removeRound: 'Remove last round',
      scoring: 'Scoring', rubric: 'Scoring rubric', rubricHint: 'What each score means. This form does not validate task difficulty or scoring reliability.',
      review: 'Protocol review', reviewedBy: 'Protocol reviewer', reviewNote: 'Protocol review notes',
      missing: 'Complete before freezing', ready: 'Required fields are complete. Check the actual content before confirming.',
      confirm: 'I reviewed the tasks, revision windows, delay, consent text and fixed model. Freeze these rules for this study.',
      freeze: 'Freeze study', freezing: 'Freezing…',
    },
    board: {
      sections: 'Study sections', reviewTab: 'Reviews', peopleTab: 'Participants', inviteTab: 'Invite', exportTab: 'Export', filters: 'Participant views', all: 'All', attention: 'Needs attention', completedFilter: 'Completed', noMatches: 'No participants match this view.', original: 'Method before revision', reviewOutcome: 'Approved revisions become available in the next round according to the frozen group rules.',
      frozen: 'Protocol frozen. Model, tasks and update rules cannot change during this study.',
      summary: 'Progress', invited: 'Invited', consented: 'Consented', active: 'In progress', complete: 'Complete', withdrawn: 'Withdrawn', pendingReviews: 'Awaiting review', failedRuns: 'Failed replies',
      reviews: 'Method revisions awaiting review', noReviews: 'No revision is waiting. Approved revisions take effect in the next round only for the update group.',
      participant: 'Participant', strategy: { 'next-round': 'Updates take effect', frozen: 'Initial method throughout' },
      revised: 'Revised method', evidence: 'Evidence and reason', reviewedBy: 'Reviewer', reason: 'Review reason', approve: 'Approve revision', reject: 'Reject revision',
      decided: { approved: 'Approved', rejected: 'Rejected', pending: 'Awaiting review' },
      participants: 'Participants', noParticipants: 'No participant links yet.',
      status: { consent: 'Not yet consented', answering: 'Working', revision: 'Deciding on the method', review: 'Revision awaiting review', waiting: 'Waiting for next round', ready: 'Next round available', complete: 'Complete', withdrawn: 'Withdrawn', expired: 'Access expired' },
      stage: { before: 'independent judgment', coaching: 'working with help', after: 'independent transfer' },
      erased: 'answers erased', round: 'Round', help: 'Agent replies', succeeded: 'completed', failed: 'failed', dueAt: 'Next round opens', lastActivity: 'Last activity', details: 'Round details', method: 'Method used', answers: 'answers', noAnswers: 'No answers yet',
      invitations: 'Participant links', invite: 'Create participant link', capacityReached: 'All invitation slots are used.', linkNote: 'Private link for one person. Anyone holding it can act as this participant; share it deliberately. It stays valid for 90 days.', copy: 'Copy link', copied: 'Copied', manual: 'Select the link and copy it.',
      exports: 'Exports', record: 'Download study record', recordNote: 'Full protocol, assignments, answers, help conversations, revisions and reviews. Store privately.',
      packet: 'Download blind review packet', packetNote: 'Numbered work items with task, answer and scoring reference only. No names, groups, method text or timestamps. Regenerate after new submissions; codes stay stable.',
      key: 'Download packet key', keyNote: 'Maps work codes back to participants, groups and method versions. Keep it away from reviewers until scoring is done.',
      refreshSnapshot: 'Refresh export snapshot', snapshotNote: 'These downloads share one snapshot. Refresh to include later changes; keep each packet with its matching key.', snapshotReady: 'Export snapshot ready.',
      exportFailed: 'The download could not start. Try again.', exportStarted: 'Download started.',
      protocol: 'Frozen protocol', rubric: 'Scoring rubric', initialMethod: 'Initial method',
    },
    participant: {
      saved: 'Study progress synced', returnHint: 'You can close this page. Return using the same private link to continue.', waitingTitle: 'This round is saved', reviewTitle: 'Revision submitted', readyTitle: 'Ready for the next round', finishedTitle: 'Thank you for taking part', consentTitle: 'Before you begin',
      loading: 'Loading saved progress…', saving: 'Saving your progress…',
      expired: 'Your study access has expired. You can still withdraw or erase your data. Contact the researcher if you need help.',
      erased: 'Your answers, methods and replies have been erased from this study.', retained: 'Your submitted data is currently retained. You can request deletion below.', eraseConfirm: 'Delete my submitted data permanently. This cannot be undone.', eraseNow: 'Erase my study data',
      title: 'Study participation', missingLink: 'Open your private participant link to begin.', check: 'Check saved progress', roundOf: (r: number, n: number) => `Round ${r} of ${n}`,
      stages: ['Independent judgment', 'Work with Agent help', 'Independent transfer'],
      stageHints: ['Answer on your own first. This answer is locked before any help.', 'Ask the Agent about the task if you wish, then submit your answer.', 'A new situation, answered without help. Earlier Agent replies are not shown.'],
      consentCheck: 'I have read the study information and agree to participate.', begin: 'Agree and begin',
      task: 'Task', previousAnswer: 'Your locked independent judgment', method: 'Method the Agent follows this round',
      help: 'Agent help', helpNote: 'Your question, the task and the fixed method are sent to the study model. Your knowledge library, other rounds and scoring references are excluded.',
      helpBudget: (s: number, sMax: number, a: number, aMax: number) => `${s} of ${sMax} completed replies · ${a} of ${aMax} attempts used`,
      question: 'Question for the Agent', ask: 'Ask for help', asking: 'Waiting for the reply… this can take up to two minutes.', helpPending: 'A reply is still being prepared. Check saved progress before asking again.',
      helpExhausted: 'The help limit for this round is reached. Submit your answer to continue.',
      runState: { pending: 'Working…', interrupted: 'This request did not finish. You can ask again.', failed: 'No complete reply was saved. You can ask again or continue without help.' },
      answer: 'Your answer', answerHint: 'Unsubmitted text stays on this device for 7 days.', confirm: 'I am ready to submit. This answer is locked afterward.', submit: 'Submit and continue', locked: 'Your answer is locked.',
      reflect: 'Reflect on the method', reflectHint: 'You can propose a revision with evidence from this round, or keep the current method.', currentMethod: 'Current method',
      revisedMethod: 'Revised method', revisionEvidence: 'Evidence and reason for the change', submitRevision: 'Submit for review', keep: 'Keep the current method',
      noWindow: 'The frozen protocol has no revision window after this round.',
      review: 'Your revision is saved and awaiting the researcher’s review.', yourRevision: 'Your submitted revision',
      waiting: 'The next round opens at', decision: { approved: 'Your revision was approved.', rejected: 'Your revision was not approved; the previous method remains.' },
      ready: 'The next round is available.', next: 'Start next round',
      complete: 'All rounds are complete. Thank you.', completeNote: 'All submitted answers are saved. You may now close this page. Your withdrawal and erasure options remain available below.',
      withdrawn: 'You have withdrawn from this study.', withdraw: 'Withdraw from this study', erase: 'Also erase my answers, methods and replies', withdrawConfirm: 'I understand this ends my participation. Erasure cannot be undone.', confirmWithdraw: 'Confirm withdrawal',
      draft: 'Unsubmitted input stays on this device for 7 days.',
      errors: { unauthorized: 'This link is not available. It may have expired or been revoked. Contact the researcher.', conflict: 'Saved progress changed. Your input is still here; check saved progress before continuing.', configuration: 'Agent help is not available right now. You can continue without help or try again later.', unavailable: 'This study is not available right now. Contact the researcher.', invalid: 'Check the required text and try again.', storage: 'The request was not confirmed. Your input is preserved; retry or check saved progress.' },
    },
  },
  zh: {
    workspace: {
      back: '研究', title: '多轮共同进化',
      lead: '两组随机分配，任务与修订机会相同。一组的审核修订从下一轮起生效，另一组全程保留初始方法。每轮区分独立作答、Agent 帮助和独立迁移。',
      refresh: '刷新已保存进度', list: '研究列表', studies: '已冻结的研究', none: '还没有多轮研究。可以在下方准备并冻结一项。',
      unavailable: '部分研究记录暂时无法读取，原文件已保留。',
      prepare: '准备新研究', open: '打开',
      participants: '位参与者', pending: '待审核', active: '进行中', complete: '已完成',
      rounds: '轮', updated: '更新于',
      readiness: '邀请参与者之前', modelReady: '固定模型', modelMissing: '请先在 AI 设置中配置兼容模型。新协议会冻结当前模型、温度和回复预算。',
      accessReady: '访问保护已开启：已配置网页密码和访问令牌。', accessMissing: '创建参与链接前，请在设置中启用网页密码和访问令牌；远程参与需使用 HTTPS。',
      settings: '打开设置', aiSettings: 'AI 设置',
      error: '保存或读取失败，输入已保留。请检查配置或刷新已保存进度。',
      errors: { configuration: '尚未配置兼容模型。请打开 AI 设置后重试。', conflict: '已保存状态发生变化，或固定模型与当前设置不一致。请先刷新已保存进度。', invalid: '有字段缺失或超出范围，请查看冻结按钮上方的清单。', unavailable: '参与链接需要网页密码、访问令牌，远程使用还需 HTTPS。', storage: '尚未确认操作结果。请重试同一操作，不会重复创建。', 'not-found': '这项研究暂不可用，请返回研究列表。', unauthorized: '登录已过期，请重新登录后再打开此页。', forbidden: '请从当前 MindOS 实例打开此页面。' },
    },
    form: {
      jump: '跳转到章节', basics: '研究', title: '研究名称', hypothesis: '检验假设', hypothesisHint: '写清什么结果会推翻这个想法，而不只是期望看到什么。',
      participantInfo: '参与者会读到的内容', consent: '知情说明', withdrawal: '退出与删除说明',
      method: '初始方法（两组相同）', methodHint: '第一轮 Agent 收到的原文。之后只有一组可能改用审核通过的修订版本。',
      runtime: '固定模型', runtimeSummary: (provider: string, model: string, temperature: number, tokens: number) => `${provider} / ${model} · 温度 ${temperature} · 每次回复 ${tokens} token（含推理）`,
      runtimeMissing: '请先在设置中配置兼容模型。',
      schedule: '人数与间隔', capacity: '邀请人数上限', capacityHint: '这是存储上限，不是样本量建议。分配按成对平衡。', delay: '轮次间隔（小时）', delayHint: '0 只用于流程检查；真实跨天返回至少填 24。',
      rounds: '轮次', round: '第', before: '帮助前独立任务', coaching: '协作练习任务', after: '新的独立迁移任务', reference: '私有评分参考',
      referenceHint: '不会展示给参与者，也不会发送给模型；会包含在盲评工作包中。',
      updateAllowed: '本轮结束后允许修订方法', finalRound: '最后一轮之后没有更新。',
      addRound: '增加轮次', removeRound: '移除最后一轮',
      scoring: '评分', rubric: '评分规则', rubricHint: '写清不同分数对应的表现。填写表单不代表题目难度或评分可靠性已验证。',
      review: '协议审核', reviewedBy: '协议审核人', reviewNote: '协议审核说明',
      missing: '冻结前还需补齐', ready: '必填内容已齐全，请核对实际材料后再确认。',
      confirm: '我已审核任务、修订窗口、间隔、知情说明与固定模型，确认冻结本研究规则。',
      freeze: '冻结研究', freezing: '正在冻结…',
    },
    board: {
      sections: '研究工作区', reviewTab: '审核', peopleTab: '参与者', inviteTab: '邀请', exportTab: '导出', filters: '参与者视图', all: '全部', attention: '需要关注', completedFilter: '已完成', noMatches: '此视图下暂无参与者。', original: '修订前的方法', reviewOutcome: '批准后，修订是否在下一轮生效由已冻结的分组规则决定。',
      frozen: '协议已冻结。模型、任务与生效规则在研究期间不能修改。',
      summary: '进度', invited: '已邀请', consented: '已同意', active: '进行中', complete: '已完成', withdrawn: '已退出', pendingReviews: '待审核', failedRuns: '失败回复',
      reviews: '待审核的方法修订', noReviews: '暂无待审核修订。批准后的修订只在“更新生效”组的下一轮起效。',
      participant: '参与者', strategy: { 'next-round': '修订下一轮生效', frozen: '全程初始方法' },
      revised: '修订后的方法', evidence: '依据与理由', reviewedBy: '审核人', reason: '审核理由', approve: '批准修订', reject: '拒绝修订',
      decided: { approved: '已批准', rejected: '已拒绝', pending: '待审核' },
      participants: '参与者', noParticipants: '还没有创建参与链接。',
      status: { consent: '尚未同意', answering: '作答中', revision: '正在决定方法', review: '修订待审核', waiting: '等待下一轮', ready: '可开始下一轮', complete: '已完成', withdrawn: '已退出', expired: '访问已到期' },
      stage: { before: '独立判断', coaching: '借助帮助', after: '独立迁移' },
      erased: '作答已删除', round: '第', help: 'Agent 回复', succeeded: '完成', failed: '失败', dueAt: '下一轮开放', lastActivity: '最近活动', details: '轮次详情', method: '使用的方法', answers: '份作答', noAnswers: '尚无作答',
      invitations: '参与链接', invite: '创建参与链接', capacityReached: '邀请名额已用完。', linkNote: '一人一份的私有链接。持有者可以该参与者身份操作，请谨慎分享；链接 90 天内有效。', copy: '复制链接', copied: '已复制', manual: '请选中链接后手动复制。',
      exports: '导出', record: '下载研究记录', recordNote: '包含完整协议、分组、作答、帮助对话、修订与审核。请妥善保管。',
      packet: '下载盲评工作包', packetNote: '编号作品只含任务、回答和评分参考，不含姓名、组别、方法原文和时间。新增作答后可重新生成，编号保持稳定。',
      key: '下载工作包密钥', keyNote: '把作品编号对回参与者、组别和方法版本。评分完成前不要交给评审者。',
      refreshSnapshot: '刷新导出快照', snapshotNote: '这些下载来自同一份快照。纳入后续变化请先刷新，并将评分材料与对应映射一起保管。', snapshotReady: '导出快照已就绪。',
      exportFailed: '下载未能开始，请重试。', exportStarted: '已发起下载。',
      protocol: '已冻结的协议', rubric: '评分规则', initialMethod: '初始方法',
    },
    participant: {
      saved: '研究进度已同步', returnHint: '可以关闭此页面，下次使用同一份私有参与链接继续。', waitingTitle: '本轮已保存', reviewTitle: '修订已提交', readyTitle: '可以开始下一轮了', finishedTitle: '感谢你的参与', consentTitle: '开始之前',
      loading: '正在读取已保存的进度…', saving: '正在保存进度…',
      expired: '研究访问已到期。你仍可退出或删除数据，如需协助请联系研究者。',
      erased: '你的作答、方法与回复已从本研究中删除。', retained: '目前仍保留你提交的数据，你可以在下方申请删除。', eraseConfirm: '永久删除我提交的数据，此操作不能撤销。', eraseNow: '删除我的研究数据',
      title: '研究参与', missingLink: '请使用你的私有参与链接进入。', check: '核对已保存进度', roundOf: (r: number, n: number) => `第 ${r} 轮，共 ${n} 轮`,
      stages: ['独立判断', '借助 Agent 帮助', '独立迁移'],
      stageHints: ['先自己作答。这份回答会在获得任何帮助之前锁定。', '可以就这项任务向 Agent 提问，然后提交你的回答。', '一个新情境，独立作答；不会显示之前的 Agent 回复。'],
      consentCheck: '我已阅读研究说明，并同意参与。', begin: '同意并开始',
      task: '任务', previousAnswer: '你已锁定的独立判断', method: '本轮 Agent 遵循的方法',
      help: 'Agent 帮助', helpNote: '你的问题、任务和固定方法会发送给研究模型。不会发送你的知识库、其他轮次或评分参考。',
      helpBudget: (s: number, sMax: number, a: number, aMax: number) => `已完成回复 ${s}/${sMax} · 已用尝试 ${a}/${aMax}`,
      question: '向 Agent 提问', ask: '请求帮助', asking: '正在等待回复，最长约两分钟。', helpPending: '上一条回复仍在处理中，请先核对进度再提问。',
      helpExhausted: '本轮帮助次数已用完，请提交你的回答继续。',
      runState: { pending: '正在处理…', interrupted: '这次请求未能完成，可以再次提问。', failed: '未获得完整回复，可以再次提问或继续作答。' },
      answer: '你的作答', answerHint: '未提交的文字在本机保留 7 天。', confirm: '我已准备好提交，并理解提交后本阶段作答将被锁定。', submit: '提交并继续', locked: '你的作答已锁定。',
      reflect: '回看本轮方法', reflectHint: '可以依据本轮证据提出修订，也可以保留当前方法。', currentMethod: '当前方法',
      revisedMethod: '修订后的方法', revisionEvidence: '修改依据与理由', submitRevision: '提交审核', keep: '保留当前方法',
      noWindow: '冻结协议规定，本轮之后不开放修订。',
      review: '修订已保存，等待研究者审核。', yourRevision: '你提交的修订',
      waiting: '下一轮开放时间', decision: { approved: '你的修订已获批准。', rejected: '你的修订未获批准，继续使用之前的方法。' },
      ready: '下一轮已可以开始。', next: '开始下一轮',
      complete: '所有轮次已完成，谢谢。', completeNote: '所有已提交的作答均已保存，可以关闭此页面。下方仍保留退出和删除数据的入口。',
      withdrawn: '你已退出研究。', withdraw: '退出本研究', erase: '同时删除我的作答、方法与回复', withdrawConfirm: '我理解这会结束我的参与，删除不能撤销。', confirmWithdraw: '确认退出',
      draft: '未提交输入在本机保留 7 天。',
      errors: { unauthorized: '这份链接暂不可用，可能已过期或被撤销，请联系研究者。', conflict: '已保存的进度发生了变化，输入已保留；请先核对已保存进度。', configuration: 'Agent 帮助暂时不可用。你可以不借助帮助继续作答，或稍后重试。', unavailable: '这项研究暂时不可用，请联系研究者。', invalid: '请检查必填文字后重试。', storage: '请求未确认完成，输入已保留；可重试或核对已保存进度。' },
    },
  },
};
export type LongitudinalCopy = typeof longitudinalCopy.en;
