import { test, expect } from '@playwright/test';

// Run against an initialized MindOS dev server. API writes are intercepted; no external Agent config is changed.
test('configures native MCP, preserves partial success and fills the mobile viewport', async ({ page, context, baseURL }) => {
 test.setTimeout(120_000);
 const base = baseURL ?? 'http://localhost:3456';
 await page.setViewportSize({width:1440,height:1100});
 const agent = { key: 'codex', name: 'Codex', installed: true, present: true, format: 'toml', entryStyle: 'codex', scope: 'global', transport: 'stdio', hasGlobalScope: true, hasProjectScope: true, preferredTransport: 'stdio', configKey: 'mcp_servers', globalPath: '~/.codex/config.toml', projectPath: '.codex/config.toml', projectRoot: '/workspace/My Knowledge', configPath: '~/.codex/config.toml', skillMode: 'universal', skillWorkspacePath: '/workspace/.agents/skills', installedSkillNames: ['mindos'], installedSkillCount: 1, configuredMcpServers: ['mindos'], configuredMcpServerCount: 1, connection: { status: 'unverified' } };
 await context.addCookies([{name:'locale',value:'zh',url:base}]);
 await context.addInitScript(() => {localStorage.setItem('locale','zh');if(!localStorage.getItem('theme'))localStorage.setItem('theme','light');});
 await context.grantPermissions(['clipboard-read','clipboard-write']);
 const errors: string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**', r=>r.request().method()==='GET' ? r.continue() : r.abort());
 await page.route('**/api/setup', r=>r.fulfill({json:{setupPending:false,walkthroughCompleted:true,guideState:{active:false,dismissed:true}}}));
 await page.route('**/api/agent-activity?*',r=>r.fulfill({json:{events:[]}}));
 let saveMode='warning'; let lastSave: {token?: string; agents: Array<{scope: string; transport: string}>};
 await page.route('**/api/mcp/agents', r=>r.fulfill({json:{agents:[agent,{...agent,key:'cursor',name:'Cursor',format:'json',entryStyle:'standard'}]}}));
 await page.route('**/api/mcp/status', r=>r.fulfill({json:{running:true,transport:'http',endpoint:'http://127.0.0.1:8567/mcp',port:8567,toolCount:36,authConfigured:true,maskedToken:'••••••••'}}));
 await page.route('**/api/mcp/token/reveal', r=>r.fulfill({json:{authToken:'fixture-secret',authConfigured:true}}));
 await page.route('**/api/skills', r=>r.fulfill({json:{skills:[]}}));
 await page.route('**/api/skills/matrix', r=>r.fulfill({json:{skills:[],agents:[],cells:{}}}));
 await page.route('**/api/mcp/install', r=>{lastSave=r.request().postDataJSON(); if(saveMode==='error')return r.fulfill({status:403,json:{error:'没有写入权限，请检查配置目录权限。'}});agent.transport=lastSave!.agents[0].transport;agent.scope=lastSave!.agents[0].scope;return r.fulfill({json:{results:[{status:'ok',verified:saveMode==='success',verifyError:saveMode==='warning'?'HTTP 401：请检查服务认证。':undefined}]}});});
 await page.route('**/api/mcp/verify', r=>r.fulfill({json:{transport:'http',verified:true}}));
 await page.goto(base+'/agents/codex',{waitUntil:'domcontentloaded',timeout:180000});
 await page.getByRole('heading',{name:'连接 MindOS',exact:true}).waitFor({timeout:90000});
 await page.getByRole('radio',{name:'本地进程',exact:true}).focus();
 await page.keyboard.press('ArrowRight');
 await expect(page.getByRole('radio',{name:'HTTP',exact:true})).toBeChecked();
 await expect(page.getByRole('button',{name:'测试已保存的连接'})).toBeDisabled();
 await page.getByRole('button',{name:'复制配置',exact:true}).click();
 await expect(page.getByText('已复制配置。',{exact:true})).toBeVisible();
 const copied = await page.evaluate(()=>navigator.clipboard.readText());
 if(!copied.includes('fixture-secret')||!copied.includes('http_headers'))throw new Error('Wrong native clipboard configuration');
 await page.screenshot({path:'/tmp/agent-workbench-'+'desktop.png',fullPage:true});
 if((await page.locator('body').innerText()).includes('fixture-secret'))throw new Error('Secret visible in UI');
 await page.getByText('当前项目',{exact:true}).click();
 await page.getByRole('button',{name:'保存配置',exact:true}).click();
 await expect(page.getByText('配置已保存，但连接尚未验证通过。',{exact:true})).toBeVisible();
 if(lastSave!.token!=='fixture-secret')throw new Error('Missing HTTP authentication');
 if(lastSave!.agents[0].scope!=='project'||lastSave!.agents[0].transport!=='http')throw new Error('Wrong saved selection');
 await page.screenshot({path:'/tmp/agent-workbench-'+'warning.png',fullPage:true});
 await page.getByRole('button',{name:'测试已保存的连接',exact:true}).click();
 await expect(page.getByText('MCP 握手已验证',{exact:true}).first()).toBeVisible();
 saveMode='error';await page.getByRole('button',{name:'保存配置',exact:true}).click();
 await expect(page.getByRole('alert').filter({hasText:'没有写入权限'})).toBeVisible();
 await page.screenshot({path:'/tmp/agent-workbench-'+'error.png',fullPage:true});
 await page.evaluate(()=>localStorage.setItem('theme','dark'));
 await page.reload({waitUntil:'domcontentloaded'});
 await page.getByRole('heading',{name:'连接 MindOS',exact:true}).waitFor();
 await expect(page.locator('html')).toHaveClass(/dark/);
 await page.screenshot({path:'/tmp/agent-workbench-'+'dark.png',fullPage:true});
 await page.evaluate(()=>localStorage.setItem('theme','light'));
 await page.reload({waitUntil:'domcontentloaded'});
 await page.getByRole('heading',{name:'连接 MindOS',exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await expect.poll(()=>page.locator('#main-content').evaluate(el=>getComputedStyle(el).paddingLeft)).toBe('0px');
 const heading=page.getByRole('heading',{name:'连接 MindOS',exact:true});
 await heading.scrollIntoViewIfNeeded();
 await expect.poll(()=>heading.evaluate(el=>el.closest('[aria-labelledby]')!.getBoundingClientRect().width)).toBeGreaterThan(280);
 await page.screenshot({path:'/tmp/agent-workbench-'+'mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 if(overflow)throw new Error('Mobile document overflows');
 expect(errors).toEqual([]);

});
