export const researchHubCopy = {
  en: {
    designs: 'Study designs', designHint: 'Choose the question you want to test', configured: (n: number) => `${n}/2 configuration checks complete`,
    multiKicker: 'Across rounds · two groups',
    multiTitle: 'Multi-round coevolution',
    multiBody: 'Does shared experience improve later collaboration? Compare reviewed method updates with a frozen method across repeated rounds of independent work, Agent help and transfer.',
    multiOpen: 'Open multi-round studies',
    multiStats: (count: number, active: number, pending: number) => count ? `${count} frozen · ${active} in progress · ${pending} awaiting review` : 'No study frozen yet',
    fourKicker: 'Four stages · comparison conditions',
    fourTitle: 'Four-stage study',
    fourBody: 'Does learning persist without the Agent? Compare initial judgment, assisted practice, independent transfer and a delayed task. Invite participants and export blind scoring materials.',
    fourStats: (count: number) => count ? `${count} draft${count === 1 ? '' : 's'} below` : 'No draft yet; start below',
    fourOpen: 'Drafts below',
    loading: 'Loading…',
    readiness: 'Before a pilot',
    modelReady: (summary: string) => `Model configured: ${summary}`,
    modelMissing: 'Configure a compatible model in AI settings. New protocols freeze the current model, temperature and reply budget.',
    aiSettings: 'AI settings',
    accessReady: 'Access protection is on: Web password and access token are configured.',
    accessMissing: 'Enable a Web password and an access token before creating participant links. Remote participation requires HTTPS.',
    settings: 'Open Settings',
    materials: 'Review tasks, scoring references and consent text yourself. Example materials are not calibrated, and completing a pilot does not show a learning effect.',
    unknown: 'Could not read readiness right now. Retry before inviting anyone.',
    retry: 'Retry',
    checklist: 'Pilot checklist',
    steps: [
      'Walk through a study yourself first, titled as a workflow trial that stays out of analysis.',
      'Set at least 24 hours between rounds for real cross-day returns; 0 is for workflow checks only.',
      'Review task difficulty, acceptable answers and scoring references before freezing.',
      'Send each private link to one consenting person only; never publish links.',
      'Review revisions on evidence and stated scope, not on which group a participant is in.',
      'Keep failed model replies as failures; retry explicitly after fixing configuration.',
      'Score from the blind review packet; open the packet key only after scoring.',
    ],
  },
  zh: {
    designs: '研究设计', designHint: '从你要检验的问题出发', configured: (n: number) => `${n}/2 项配置已完成`,
    multiKicker: '跨轮次 · 两组对照',
    multiTitle: '多轮共同进化',
    multiBody: '共享经验能否改善后续协作？在多轮独立判断、Agent 帮助与迁移中，对照“审核后的方法更新”与“全程初始方法”。',
    multiOpen: '打开多轮研究',
    multiStats: (count: number, active: number, pending: number) => count ? `${count} 项已冻结 · ${active} 位进行中 · ${pending} 份待审核` : '尚未冻结研究',
    fourKicker: '四阶段 · 多条件对照',
    fourTitle: '四阶段研究',
    fourBody: '离开 Agent 后，学习能否保留？比较初始判断、协作练习、独立迁移与延迟任务，支持参与者邀请及盲评材料导出。',
    fourStats: (count: number) => count ? `下方有 ${count} 份草稿` : '还没有草稿，从下方开始',
    fourOpen: '草稿在下方',
    loading: '正在读取…',
    readiness: '试跑之前',
    modelReady: (summary: string) => `模型已配置：${summary}`,
    modelMissing: '请先在 AI 设置中配置兼容模型。新协议会冻结当前模型、温度和回复预算。',
    aiSettings: 'AI 设置',
    accessReady: '访问保护已开启：已配置网页密码和访问令牌。',
    accessMissing: '创建参与链接前，请启用网页密码和访问令牌；远程参与需使用 HTTPS。',
    settings: '打开设置',
    materials: '题目、评分参考与知情说明需由负责人自行审核。示例材料未经校准，完成试跑也不代表学习效果。',
    unknown: '暂时无法读取就绪状态，邀请前请重试。',
    retry: '重试',
    checklist: '试跑清单',
    steps: [
      '负责人先自己走一遍，标题注明流程试用、不纳入分析。',
      '真实跨天返回至少间隔 24 小时；0 小时只用于流程检查。',
      '冻结前审核题目难度、可接受答案和评分参考。',
      '每份私有链接只发给一位已同意的参与者，不公开发布。',
      '依据证据和范围声明审核修订，不因组别改变标准。',
      '模型失败保留为失败；修复配置后再显式重试。',
      '用盲评工作包评分，评分完成后再打开工作包密钥。',
    ],
  },
};
