export const studyCopy = {
  en: {
    title: 'Research', lead: 'Prepare a question, comparison conditions and the evidence you will assess. Choose a design, check readiness, then invite people you have consented in person.', draftsTitle: 'Four-stage study drafts',
    limit: 'For local preparation. Participant access supports workflow pilots; isolated chat can be enabled in a new protocol; independent reviewers use separate work packets. Validate materials and actual model execution before a study.',
    back: 'Human growth', all: 'All study drafts', create: 'New study draft', empty: 'No study materials yet', emptyHint: 'Start with the question. You can save incomplete materials and return later.',
    loading: 'Loading saved materials…', busy: 'Saving…', save: 'Save draft', saved: 'Saved locally', reviewPending: 'Review notes are saved when materials are frozen', reviewRecord: 'Freeze review record', copy: 'Copy materials to a new draft', copySuffix: ' — Copy', dirty: 'Unsaved changes',
    untitled: 'Untitled study', draft: 'Draft', frozen: 'Frozen', unavailable: 'Some records could not be read. Available drafts are shown; existing files were preserved.',
    steps: ['Question', 'Conditions', 'Tasks', 'Scoring', 'Review'], next: 'Next section', previous: 'Previous section',
    capacity: 'Enrollment limit', capacityHint: 'Storage limit, not a sample-size recommendation. Choose the study size after piloting.', delay: 'Delay after the new-situation task (days)',
    condition: 'Condition', addCondition: 'Add condition', removeCondition: 'Remove this condition', conditionHint: 'Describe what changes between conditions. These are planned settings; no Agent has been run.', tools: 'Planned tools (one per line; leave empty for none)',
    phases: ['Initial judgment', 'Practice with help', 'New situation', 'Delayed situation'], taskHint: 'Scoring references stay separate from participant task projections.', budget: 'Task time budget (seconds)',
    criterion: 'Criterion', addCriterion: 'Add scoring criterion', removeCriterion: 'Remove this criterion', scoreMax: 'Highest score', rubricHint: 'Describe what each score means. Completing this form does not validate task difficulty or scoring reliability.',
    reviewTitle: 'Review the materials before freezing', missing: 'Complete these fields', ready: 'Required fields are complete. Check the actual content before confirming.', unsavedReview: 'Save your changes before freezing this version.',
    reviewedBy: 'Reviewer code', reviewerHint: 'Lowercase letters, numbers and hyphens, starting with a letter. This records your declaration; it is not independent review.', reviewNote: 'What did you check?',
    confirm: 'I checked these materials and understand that freezing prevents further edits to this version.', freeze: 'Freeze reviewed materials', frozenTitle: 'Materials frozen', frozenHint: 'This version is read-only. Freezing does not start a study or enroll anyone.',
    leave: 'You have unsaved changes. Leave and discard them?', remove: 'Remove this section and its current text?', refresh: 'Reload saved version', retry: 'Retry loading', none: 'None',
    errors: { storage: 'Saving was not confirmed. Your text is still here; keep this page open and retry.', conflict: 'The saved version changed. Your text is still here. Reload the saved version only when you are ready to discard these edits.', invalid: 'Check the field lengths and number ranges, then try again.', 'not-found': 'This study is unavailable. Return to the study list.', unauthorized: 'Your session expired. Sign in again; keep this draft open until it is saved.', forbidden: 'Open research preparation from this MindOS instance to continue.' },
  },
  zh: {
    title: '研究', lead: '先明确问题、比较条件，以及准备用什么证据判断结果。选择研究设计，核对就绪状态，再邀请已当面同意的参与者。', draftsTitle: '四阶段研究草稿',
    limit: '用于本机准备材料。参与者入口支持流程试跑，新协议可启用独立聊天帮助，独立评审使用单独的工作包。正式研究前仍需验证材料和真实模型执行。',
    back: '人的成长', all: '全部研究草稿', create: '新建研究草稿', empty: '还没有研究材料', emptyHint: '从想检验的问题开始。没填完也能保存，之后再继续。',
    loading: '正在读取已保存的材料…', busy: '正在保存…', save: '保存草稿', saved: '已保存到本机', reviewPending: '核对说明将在冻结材料时保存', reviewRecord: '冻结核对记录', copy: '复制材料为新草稿', copySuffix: ' — 副本', dirty: '有未保存的修改',
    untitled: '未命名研究', draft: '草稿', frozen: '已冻结', unavailable: '部分记录暂时无法读取。其余草稿仍可打开，原文件已保留。',
    steps: ['问题', '比较条件', '任务材料', '评分标准', '核对'], next: '下一部分', previous: '上一部分',
    capacity: '可登记人数上限', capacityHint: '这是存储上限，不是样本量建议；正式研究规模应在先导后确定。', delay: '新情境任务后的间隔（天）',
    condition: '条件', addCondition: '添加比较条件', removeCondition: '移除当前条件', conditionHint: '说明条件之间改变了什么。这里记录拟用配置，尚未运行 Agent。', tools: '拟用工具（每行一项；不用工具可留空）',
    phases: ['初始判断', '获得帮助的练习', '新情境', '延迟新情境'], taskHint: '评分参考与参与者可见的题目分别保存和呈现。', budget: '任务时间预算（秒）',
    criterion: '评分维度', addCriterion: '添加评分维度', removeCriterion: '移除当前维度', scoreMax: '最高分', rubricHint: '写清不同分数对应的表现。填完表单不代表题目难度或评分可靠性已验证。',
    reviewTitle: '冻结前核对材料', missing: '还需要补齐这些内容', ready: '必填内容已齐全，请核对实际材料后再确认。', unsavedReview: '请先保存修改，再冻结这个版本。',
    reviewedBy: '审核者代号', reviewerHint: '用小写字母开头，可含数字和连字符。这里只记录你的确认，不代表独立评审。', reviewNote: '这次核对了什么？',
    confirm: '我已核对这些材料，并理解冻结后不能继续修改这个版本。', freeze: '冻结已核对的材料', frozenTitle: '材料已冻结', frozenHint: '这个版本现在只读。冻结不会开始研究或登记参与者。',
    leave: '还有未保存的修改。要放弃这些修改并离开吗？', remove: '要移除这一部分及已填写的内容吗？', refresh: '重新读取已保存版本', retry: '重新读取', none: '无',
    errors: { storage: '尚未确认保存成功。当前输入仍保留，请保留页面并重试。', conflict: '已保存的版本发生了变化，你填写的内容仍在。准备好放弃当前修改时，再重新读取已保存版本。', invalid: '请检查文字长度和数字范围，再试一次。', 'not-found': '这项研究暂不可用，请返回研究列表。', unauthorized: '登录已过期。请重新登录，并在保存前保留当前草稿页面。', forbidden: '请从当前 MindOS 实例打开研究准备页面。' },
  },
};
export type StudyCopy = typeof studyCopy.en;
