export const comparisonCopy = {
  en: {
    title: 'Compare method versions', lead: 'Check what a revision changes on the same tasks. Your cases and judgments are exploratory evidence, not a measured learning effect.',
    old: 'Earlier version', next: 'Later version', version: 'Version', choose: 'Saved comparison', new: 'New comparison', back: 'Back to results',
    method: 'Material sent to each run', material: 'Each run receives only the selected version’s behavior, scope and observable check, plus one task. Source conversations, other tasks and your criteria stay out of the request.',
    behavior: 'Behavior', scope: 'Scope and exceptions', check: 'Observable check',
    use: 'Where the method should apply', exception: 'Where an exception matters', retention: 'An existing ability to preserve', task: 'Task', expected: 'What would count as a good answer?',
    repetitions: 'Runs per case and version', budget: 'requests, up to {tokens} tokens each, including reasoning. Requests run one at a time. Provider charges may apply; this is a token cap, not a price estimate.',
    runtime: 'Fixed model', unavailable: 'A compatible isolated chat model is not configured. Existing comparisons remain readable. Choose an available compatible model in Settings, then refresh.',
    fixed: 'Freeze the two versions, cases and budget', frozen: 'Frozen comparison', frozenHint: 'The everyday active method is unchanged. Every attempt starts with the same fixed settings and a fresh context.',
    run: 'Run remaining tasks', retry: 'Retry this task once', stop: 'Stop running', stopping: 'Stopping…', running: 'Running one task…', waiting: 'Not run', succeeded: 'Output received', failed: 'Run failed', unknown: 'Result unknown',
    unknownHint: 'The request may have reached the provider. Refresh to check its saved state. After two minutes without a result, an explicit new attempt is available.',
    failureHint: 'This attempt is retained. A retry is a new request and may incur another charge.',
    provider: 'The provider did not return a usable response.', configuration: 'The frozen model configuration is no longer available.', interrupted: 'The request was interrupted.', 'invalid-output': 'The returned output was incomplete or unsupported.',
    mismatch: 'The provider reported a different model. Treat this as a configuration difference when comparing.', missingModel: 'The provider did not report a model identity.',
    repeat: 'Repeat', attempt: 'Attempt', refresh: 'Check saved state', export: 'Download comparison', loading: 'Loading…', partial: 'Some saved comparisons could not be read.',
    judgment: 'My judgment', outcome: 'Against this case’s criterion', met: 'Met the criterion', missed: 'Missed the criterion', uncertain: 'Uncertain', quote: 'Exact quotation from this output', reason: 'Why?', save: 'Save judgment', history: 'Earlier judgments', saved: 'Judgment saved',
    unsaved: 'This comparison has unsaved input. Discard it and continue?', error: 'This request could not be completed. Your input is still here. Check saved state before trying again.', conflict: 'The saved record or model configuration changed. Check saved state before continuing.', invalid: 'Check the two versions, three different tasks and exact output quotation.',
  },
  zh: {
    title: '比较方法版本', lead: '在相同任务上检查修订改变了什么。自选案例与自己的判定是探索性证据，不代表已测量的学习效果。',
    old: '较早版本', next: '较新版本', version: '版本', choose: '已保存的比较', new: '新建比较', back: '返回结果',
    method: '每次运行使用的材料', material: '每次只发送所选版本的行为、适用范围和观察标准，以及一道任务。原始对话、其他题目和你的判定标准不会随请求发送。',
    behavior: '行为', scope: '适用范围与例外', check: '观察标准',
    use: '应当使用方法的案例', exception: '需要识别例外的案例', retention: '应当保留的原有能力', task: '任务', expected: '怎样的回答才算符合预期？',
    repetitions: '每个案例、每个版本的运行次数', budget: '次请求，每次最多 {tokens} 个 token（含推理），依次运行。提供方可能收费；这里是用量上限，不是价格估算。',
    runtime: '固定模型', unavailable: '尚未配置可用的隔离聊天模型。已保存的比较仍可查看。请在设置中选择可用的兼容模型，再刷新。',
    fixed: '冻结版本、案例与预算', frozen: '已冻结的比较', frozenHint: '日常启用的方法保持原样。每次尝试使用固定配置，从独立的新上下文开始。',
    run: '运行剩余任务', retry: '再试一次这道任务', stop: '停止运行', stopping: '正在停止…', running: '正在运行一道任务…', waiting: '尚未运行', succeeded: '已收到输出', failed: '运行失败', unknown: '结果未知',
    unknownHint: '请求可能已经到达提供方。请刷新核对已保存状态。两分钟仍未收到结果后，可以显式发起一次新尝试。',
    failureHint: '本次尝试会保留。重试将发起新请求，可能再次计费。',
    provider: '提供方未返回可用响应。', configuration: '已冻结的模型配置目前不可用。', interrupted: '请求已中断。', 'invalid-output': '返回的内容不完整或格式不受支持。',
    mismatch: '提供方报告的模型与冻结配置不同，比较时需要考虑这一差异。', missingModel: '提供方没有报告模型身份。',
    repeat: '重复', attempt: '尝试', refresh: '核对已保存状态', export: '下载比较记录', loading: '正在读取…', partial: '部分比较记录暂时无法读取。',
    judgment: '我的判定', outcome: '对照本案例的标准', met: '符合标准', missed: '未符合标准', uncertain: '尚不确定', quote: '引用这份输出的原文', reason: '判定理由', save: '保存判定', history: '之前的判定', saved: '判定已保存',
    unsaved: '比较中还有未保存的输入。要放弃并继续吗？', error: '这次请求未能完成，输入仍在。请先核对已保存状态，再决定是否重试。', conflict: '记录或模型配置已经变化，请核对已保存状态后继续。', invalid: '请检查两个版本、三个不同任务，以及引用是否来自原文。',
  },
};
export type ComparisonCopy = typeof comparisonCopy.en;
