export const methodHandoffCopy = {
  en: {
    title: 'Hand this method to another Agent',
    lead: 'Choose a completed use of this method, review what to pass on, then try both cases with a different Agent.',
    noSource:
      'Complete a case and read its actual run here before creating a handoff.',
    source: 'Which completed run are you continuing from?',
    target: 'Receiving Agent',
    select: 'Choose one',
    rationale: 'Why are you passing on this method?',
    material: 'Review the approved method that will be attached',
    counterexamples: 'Counterexamples to include (optional)',
    unassessed:
      'These are user-reported observations, not independently assessed findings.',
    context:
      'Each case opens a fresh conversation with the approved file and your selected notes. The source conversation and response are not added. The receiving Agent’s usual workspace, tools and context settings still apply; this is not an isolated experiment.',
    save: 'Save this handoff',
    refresh: 'Reload material and Agents',
    saving: 'Loading or saving…',
    error:
      'Could not load handoff material or Agents. Your input is kept; retry when ready.',
    unavailable: 'Unavailable',
    new: 'Create another handoff',
    back: 'Back to the saved handoff',
    choose: 'Saved handoff',
    use: 'Applicable case',
    exception: 'Exception case',
    prepareUse: 'Prepare the applicable case',
    prepareException: 'Prepare the exception case',
    noRun: 'Not run yet',
    returned: 'Output received',
    assessed: 'Assessment saved',
    retry: 'Run did not complete',
    active: 'Run in progress',
    mismatch: 'A different Agent actually ran this case.',
    review: 'Review this output',
    status:
      'Review both cases separately. Saved assessments are your judgments, not a certificate of successful inheritance.',
    limit:
      'This check has reached its handoff limit. Existing packets and results remain available.',
    emptyAgents:
      'No different available Agent. Reload after enabling one in Agents.',
    paused:
      'The method is unavailable. Saved packets and results remain readable.',
  },
  zh: {
    title: '把方法交接给另一个 Agent',
    lead: '选择一次已完成的方法使用，核对要交接的内容，再让另一个 Agent 分别处理两个案例。',
    noSource: '请先完成一个案例，并在这里读取实际运行，再创建交接。',
    source: '从哪次已完成的使用继续？',
    target: '接收方法的 Agent',
    select: '请选择',
    rationale: '为什么要把这个方法交给它？',
    material: '核对将附带的已批准方法',
    counterexamples: '选择要附带的反例（可选）',
    unassessed: '这些是用户记录的观察，尚未经独立评估。',
    context:
      '每个案例都会打开新会话，附带批准的方法文件和你选择的说明；不会加入来源会话及其回复。接收 Agent 原有的工作区、工具和上下文设置仍然适用，因此这不是隔离实验。',
    save: '保存这次交接',
    refresh: '重新读取材料与 Agent',
    saving: '正在读取或保存…',
    error: '暂时无法读取交接材料或 Agent。输入仍保留，请稍后重试。',
    unavailable: '不可用',
    new: '另建一次交接',
    back: '回到已保存的交接',
    choose: '已保存的交接',
    use: '适用案例',
    exception: '反例案例',
    prepareUse: '准备适用案例',
    prepareException: '准备反例案例',
    noRun: '尚未运行',
    returned: '已收到输出',
    assessed: '已保存核对',
    retry: '运行未完成',
    active: '正在运行',
    mismatch: '实际执行的是另一个 Agent。',
    review: '核对这条输出',
    status:
      '请分别核对两个案例。已保存的核对是你的判断，不代表系统认证“继承成功”。',
    limit: '这组检验已达到交接数量上限，已有材料和结果仍可回看。',
    emptyAgents: '暂无其他可用 Agent。请在智能体中启用后重新读取。',
    paused: '方法暂不可用，已保存的交接材料和结果仍可查看。',
  },
};
