export const transferCopy = {
 en: {
  sourceUnavailable: 'The original learning record is unavailable. Saved private practice is loaded separately.',
  title: 'Try an independent judgment', intro: 'Practice evidence and conclusions with three short fictional situations. First commit your own judgment, then choose help, try a fresh situation, and return in seven days. This practice is optional and is not a validated ability test.',
  step: 'Step', sameSituation: 'Second answer to the same situation', repeatedTag: 'Pack opened before', familiarTag: 'Reported familiar', reportedConfidence: 'Reported confidence',
  unsentDraft: 'Unsent draft',
  start: 'Start this practice', loading: 'Loading practice…', saving: 'Saving…', retry: 'Retry', refresh: 'Check again',
  privacy: 'Answers and future tasks are kept in private local storage, outside normal knowledge retrieval. Submitted answers stay as they were; you can end the practice at any point.',
  stages: { baseline: 'Your initial judgment', coaching: 'Reconsider with help', transfer: 'A fresh situation', waiting: 'Come back for a fresh situation', delayed: 'A delayed fresh situation', complete: 'Compare your judgments', ended: 'Practice ended' },
  independentHint: 'The help pane is folded away when this step begins. Use your own judgment before looking for help. If you use notes or another Agent, report it below. We cannot verify outside assistance.',
  lock: 'Lock my initial answer', coached: 'Save and try a new situation', transfer: 'Save this independent attempt', delayed: 'Save and compare my answers',
  answer: 'What is your judgment, and why?', confidence: 'Confidence, from 0 to 100 (optional)',
  assistance: 'Apart from hints on this page, what did you use?', choose: 'Choose honestly', assistanceOptions: { none: 'No outside help', notes: 'My notes or other sources', agent: 'An Agent or AI tool' },
  familiar: 'Had you seen this situation before?', familiarOptions: { no: 'No', yes: 'Yes, or something substantially the same' },
  hint: 'Show a reasoning hint', yourFirst: 'Your locked initial answer', agent: 'Prepare a question for an Agent', agentPrepared: 'A question was prepared; this does not establish that an Agent answered it. If you used its help, report that when saving.',
  agentPrompt: 'Help me examine the reasoning in this fictional practice situation. Explain the evidence boundary and possible alternative explanations. Do not assess my general ability.',
  waiting: 'Your immediate attempt is saved. The next situation stays hidden until the return date. Taking a break, using help, or leaving a question unanswered does not count as a failure.', due: 'Return date', beginDelayed: 'Begin the delayed situation',
  exposure: 'This task pack was already opened in this knowledge base. These responses will be marked as previously exposed practice, not unseen independent evidence.',
  stop: 'End this practice', stopHint: 'Ending preserves your submitted answers and records the unfinished step. It does not reveal future tasks. You can review this record, but it will not restart.', stopped: 'Stop here and keep my answers', skipped: 'End without answering this step', timeout: 'End because I ran out of time',
  outcomes: { stopped: 'Stopped by choice', skipped: 'Step left unanswered', timeout: 'Ended after running out of time' },
  reviewHint: 'Compare the reasoning, not just the wording. These situations are not calibrated for equal difficulty; differences are not a measured growth score. The reference is illustrative, not an independent assessment.',
  reference: 'Reference for reflection', criteria: 'What to examine', independent: 'Reported independent, without prior exposure', supported: 'Help used, familiar material, or practice after help', export: 'Export this record',
  errors: { invalid: 'Complete the required fields, keep the answer within 4,000 characters, and use a confidence from 0 to 100 or leave it blank.', conflict: 'This practice changed or this step is unavailable. Your draft is preserved. Reload the saved state before retrying.', storage: 'Could not load or save the practice. Your draft is preserved; please retry.', 'not-found': 'The source or practice is no longer available.' },
 },
 zh: {
  sourceUnavailable: '原学习记录暂时不可用。会单独读取已保存的独立练习。',
  title: '先独立判断一次', intro: '用三个简短的虚构情境练习证据判断：先提交自己的判断，再自选帮助、换个情境尝试，七天后再回来。这是可选练习，不是经过验证的能力测验。',
  step: '步骤', sameSituation: '对同一情境再次作答', repeatedTag: '以前打开过这套材料', familiarTag: '自报熟悉材料', reportedConfidence: '自报把握程度',
  unsentDraft: '未提交的草稿',
  start: '开始这组练习', loading: '正在读取练习…', saving: '正在保存…', retry: '重试', refresh: '重新检查',
  privacy: '答案与后续题目保存在独立的本地私有目录，不参与普通知识库检索。已提交的答案会保留原样；你随时可以结束练习。',
  stages: { baseline: '先写下自己的判断', coaching: '借助帮助重新考虑', transfer: '换一个新情境', waiting: '过几天，再试一个新情境', delayed: '延迟后的新情境', complete: '对照自己的判断', ended: '练习已结束' },
  independentHint: '进入这一步时会收起帮助面板。请先依靠自己的判断。如果查看了笔记或使用其他 Agent，请在下面如实标注。系统无法核实你是否使用了外部帮助。',
  lock: '提交并锁定初始判断', coached: '保存，再换个情境', transfer: '保存这次独立尝试', delayed: '保存并对照我的答案',
  answer: '你的判断是什么？依据是什么？', confidence: '有多大把握？0–100（可选）',
  assistance: '除了本页提示，你还借助了什么？', choose: '按实际情况选择', assistanceOptions: { none: '没有其他帮助', notes: '自己的笔记或其他资料', agent: 'Agent 或 AI 工具' },
  familiar: '以前见过这个情境吗？', familiarOptions: { no: '没有', yes: '见过，或内容实质相同' },
  hint: '查看一个推理提示', yourFirst: '已锁定的初始判断', agent: '准备一个向 Agent 请教的问题', agentPrepared: '请教问题已准备。这不代表 Agent 已经回答；如果实际采用了帮助，保存时请如实标注。',
  agentPrompt: '请帮我检查这段虚构练习材料中的推理，解释证据边界和可能的替代解释。不要据此评价我的一般能力。',
  waiting: '这次新情境的答案已保存。到回看日期后，才会展示下一题。休息、借助帮助或留下未答题目，都不会被记作失败。', due: '回看日期', beginDelayed: '开始延迟练习',
  exposure: '这套材料以前已在当前知识库中打开过。这次会标记为重复接触的练习，不作为未见材料上的独立证据。',
  stop: '结束这次练习', stopHint: '保留已经提交的答案，并记录停在哪一步；不会展示未来题目。结束后可回看记录，但不会重新开始这条练习。', stopped: '到这里结束，保留答案', skipped: '这一步不作答，结束练习', timeout: '时间不够，结束练习',
  outcomes: { stopped: '主动结束', skipped: '这一步未作答', timeout: '时间不足而结束' },
  reviewHint: '对照推理依据，而不只是措辞。这些情境尚未校准为相同难度，答案差异不能当作成长分。参考解读用于复盘，不是独立评估。',
  reference: '供复盘的参考解读', criteria: '可以检查什么', independent: '自报独立作答，且未标记重复接触', supported: '使用帮助、熟悉材料或接受帮助后的练习', export: '导出这条练习',
  errors: { invalid: '请完成必填项，答案不超过 4,000 字符，把握程度填写 0–100 或留空。', conflict: '记录已改变或当前步骤暂不可用。输入仍保留，请重新读取已保存状态后再试。', storage: '暂时无法读取或保存练习。输入仍保留，请重试。', 'not-found': '来源或练习暂时不可用。' },
 },
};
export type TransferCopy = typeof transferCopy.en;
