export const QUICKADD_WORKFLOW_PROBE_FIXTURE = {
  choiceId: 'mindos-capture',
  choiceName: 'MindOS Capture',
  targetPath: 'Inbox/quickadd-capture.md',
  captureContent: 'Captured by QuickAdd fixture',
} as const;

export const QUICKADD_TEMPLATE_WORKFLOW_PROBE_FIXTURE = {
  choiceId: 'mindos-template',
  choiceName: 'MindOS Template',
  templatePath: 'Templates/quickadd-template.md',
  templateContent: '# QuickAdd Template Fixture\n\nCreated by QuickAdd template fixture.\n',
  targetFolder: 'Generated',
  fileNameFormat: 'quickadd-template-note',
  targetPath: 'Generated/quickadd-template-note.md',
} as const;

export function buildQuickAddWorkflowProbeDataJson(version = '0.0.0'): Record<string, unknown> {
  return {
    choices: [
      {
        id: QUICKADD_WORKFLOW_PROBE_FIXTURE.choiceId,
        name: QUICKADD_WORKFLOW_PROBE_FIXTURE.choiceName,
        type: 'Capture',
        command: true,
        onePageInput: 'never',
        captureTo: QUICKADD_WORKFLOW_PROBE_FIXTURE.targetPath,
        captureToActiveFile: false,
        captureToCanvasNodeId: '',
        activeFileWritePosition: 'cursor',
        createFileIfItDoesntExist: {
          enabled: true,
          createWithTemplate: false,
          template: '',
        },
        format: {
          enabled: true,
          format: QUICKADD_WORKFLOW_PROBE_FIXTURE.captureContent,
        },
        useSelectionAsCaptureValue: false,
        prepend: false,
        appendLink: false,
        task: false,
        insertAfter: {
          enabled: false,
          after: '',
          insertAtEnd: false,
          considerSubsections: false,
          createIfNotFound: false,
          createIfNotFoundLocation: 'bottom',
          inline: false,
          replaceExisting: false,
          blankLineAfterMatchMode: 'auto',
        },
        insertBefore: {
          enabled: false,
          before: '',
          createIfNotFound: false,
          createIfNotFoundLocation: 'bottom',
        },
        newLineCapture: {
          enabled: false,
          direction: 'below',
        },
        openFile: false,
        fileOpening: {
          location: 'tab',
          direction: 'vertical',
          mode: 'default',
          focus: false,
        },
        templater: {
          afterCapture: 'none',
        },
      },
      {
        id: QUICKADD_TEMPLATE_WORKFLOW_PROBE_FIXTURE.choiceId,
        name: QUICKADD_TEMPLATE_WORKFLOW_PROBE_FIXTURE.choiceName,
        type: 'Template',
        command: true,
        onePageInput: 'never',
        templatePath: QUICKADD_TEMPLATE_WORKFLOW_PROBE_FIXTURE.templatePath,
        folder: {
          enabled: true,
          folders: [QUICKADD_TEMPLATE_WORKFLOW_PROBE_FIXTURE.targetFolder],
          chooseWhenCreatingNote: false,
          createInSameFolderAsActiveFile: false,
          chooseFromSubfolders: false,
        },
        fileNameFormat: {
          enabled: true,
          format: QUICKADD_TEMPLATE_WORKFLOW_PROBE_FIXTURE.fileNameFormat,
        },
        appendLink: false,
        openFile: false,
        fileOpening: {
          location: 'tab',
          direction: 'vertical',
          mode: 'default',
          focus: false,
        },
        fileExistsBehavior: {
          kind: 'apply',
          mode: 'overwrite',
        },
      },
    ],
    inputPrompt: 'single-line',
    persistInputPromptDrafts: true,
    useSelectionAsCaptureValue: false,
    searchNestedChoices: true,
    devMode: false,
    templateFolderPath: '',
    announceUpdates: 'none',
    version,
    globalVariables: {},
    onePageInputEnabled: false,
    disableOnlineFeatures: true,
    enableRibbonIcon: false,
    showCaptureNotification: true,
    showInputCancellationNotification: false,
    enableTemplatePropertyTypes: false,
    migrations: {
      migrateToMacroIDFromEmbeddedMacro: true,
      useQuickAddTemplateFolder: true,
      incrementFileNameSettingMoveToDefaultBehavior: true,
      consolidateFileExistsBehavior: true,
      repairTemplateFileExistsBehavior: true,
      mutualExclusionInsertAfterAndWriteToBottomOfFile: true,
      setVersionAfterUpdateModalRelease: true,
      addDefaultAIProviders: true,
      removeMacroIndirection: true,
      migrateFileOpeningSettings: true,
      backfillFileOpeningDefaults: true,
      setProviderModelDiscoveryMode: true,
      migrateProviderApiKeysToSecretStorage: true,
    },
  };
}
