import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { beforeEach, afterEach, it, expect, vi } from 'vitest';
import { NextRequest } from 'next/server';
import { createStudy, freezeStudy, issueStudyInvitation } from '@geminilight/mindos/knowledge';
import { GET, PATCH } from '@/app/api/study/participate/[id]/route';
import { POST } from '@/app/api/study/participate/[id]/session/route';
import { GET as listInvitations, POST as issueInvitation, PATCH as revokeInvitation } from '@/app/api/echo/research/invitations/route';
import { verifyJwt } from '@/lib/jwt';
import { readRuntimeAuthConfig } from '@/lib/runtime-auth-config';
import { blankStudyProtocol, studyFields, changeDraft } from '@/components/echo/research/study-draft';
import { testMindRoot } from '../setup';
vi.mock('@/lib/runtime-auth-config', () => ({ readRuntimeAuthConfig: vi.fn(() => ({ authToken: 'owner-token', webPassword: 'owner-password', webSessionSecret: 'session-secret' })) }));
vi.mock('@/lib/study-coaching-executor', () => ({ executeStudyCoaching: vi.fn() }));
vi.mock('@/lib/jwt', () => ({ verifyJwt: vi.fn(async () => ({ exp: 9999999999 })) }));
let home: string;
beforeEach(() => { home = fs.mkdtempSync(path.join(os.tmpdir(), 'participant-api-')); vi.spyOn(os, 'homedir').mockReturnValue(home); vi.mocked(readRuntimeAuthConfig).mockReturnValue({ authToken: 'owner-token', webPassword: 'owner-password', webSessionSecret: 'session-secret' }); });
afterEach(() => { vi.restoreAllMocks(); fs.rmSync(home, { recursive: true, force: true }); });
function prepared() { let protocol = blankStudyProtocol('en'); for (const field of studyFields(protocol, 'en'))
    protocol = changeDraft(protocol, field.path, 'PRIVATE ' + field.path); protocol.title = 'Synthetic study'; protocol.consent = 'Consent to synthetic QA'; protocol.withdrawal = 'Stop or erase'; const d = createStudy(testMindRoot, { requestId: 'participant-api', protocol }); const s = freezeStudy(testMindRoot, d.id, { version: d.version, confirmed: true, reviewedBy: 'owner', reviewNote: 'QA' }); const i = issueStudyInvitation(testMindRoot, s.id, { requestId: 'one-invite', protocolHash: s.protocolHash, expiresAt: new Date(Date.now() + 86400000).toISOString() }); return { s, i, ctx: { params: Promise.resolve({ id: s.id }) } }; }
const request = (id: string, method = 'GET', body?: unknown, cookie = '', extra: Record<string, string> = {}) => new NextRequest('http://localhost/api/study/participate/' + id, { method, headers: { Cookie: cookie, ...extra }, ...(body ? { body: JSON.stringify(body) } : {}) });
it('exchanges only a study invitation for a scoped HttpOnly session and exposes no future materials', async () => {
    const { s, i, ctx } = prepared();
    expect((await GET(request(s.id), ctx)).status).toBe(401);
    expect((await GET(request(s.id, 'GET', undefined, '', { Authorization: 'Bearer owner-token' }), ctx)).status).toBe(401);
    const session = await POST(request(s.id, 'POST', { token: i.token }), ctx);
    expect(session.status).toBe(200);
    const setCookie = session.headers.get('set-cookie')!;
    expect(setCookie).toContain('HttpOnly');
    expect(setCookie).toContain('SameSite=strict');
    expect(setCookie).toContain('Path=/api/study/participate/' + s.id);
    const cookie = setCookie.split(';')[0]!;
    const rejectedSwitch = await POST(request(s.id, 'POST', { token: 'x'.repeat(43) }, cookie), ctx);
    expect(rejectedSwitch.status).toBe(401);
    expect(rejectedSwitch.headers.get('set-cookie')).toContain('Max-Age=0');
    const consent = await GET(request(s.id, 'GET', undefined, cookie), ctx);
    expect(consent.headers.get('cache-control')).toContain('no-store');
    expect(consent.headers.get('access-control-allow-origin')).toBeNull();
    expect(JSON.stringify(await consent.json())).not.toContain('PRIVATE');
    const joined = await PATCH(request(s.id, 'PATCH', { action: 'join', protocolHash: s.protocolHash, consentAccepted: true }, cookie), ctx);
    expect(joined.status).toBe(200);
    const result = await joined.json();
    expect(result.view.kind).toBe('participant');
    expect((await PATCH(request(s.id, 'PATCH', { action: 'open', version: result.view.participant.version, participantId: 'injected' }, cookie), ctx)).status).toBe(400);
    const opened = await PATCH(request(s.id, 'PATCH', { action: 'open', version: result.view.participant.version }, cookie), ctx);
    const value = JSON.stringify(await opened.json());
    expect(value).toContain('PRIVATE tasks.0.prompt');
    expect(value).not.toMatch(/tasks.1|reference|expectedRuntime|rubric/);
    const state = await GET(request(s.id, 'GET', undefined, cookie), ctx);
    const stateView = (await state.json()).view;
    const saved = await PATCH(request(s.id, 'PATCH', { action: 'answer', version: stateView.participant.version, answer: 'QA', confidence: null, assistance: 'none', familiar: false }, cookie), ctx);
    const savedView = (await saved.json()).view;
    expect((await PATCH(request(s.id, 'PATCH', { action: 'answer', version: stateView.participant.version, answer: 'Retry after a lost response', confidence: null, assistance: 'none', familiar: false }, cookie), ctx)).status).toBe(409);
    expect((await PATCH(request(s.id, 'PATCH', { action: 'open', version: savedView.participant.version }, cookie), ctx)).status).toBe(503);
});
it('fails closed for open instances, other origins, malformed secrets and unsupported payloads', async () => {
    const { s, i, ctx } = prepared();
    for (const body of [{ token: 'owner-token' }, { token: i.token, role: 'researcher' }, { token: 'x'.repeat(1000) }])
        expect((await POST(request(s.id, 'POST', body), ctx)).status).not.toBe(200);
    expect((await POST(request(s.id, 'POST', { token: i.token }, '', { Origin: 'https://elsewhere.example' }), ctx)).status).toBe(403);
    vi.mocked(readRuntimeAuthConfig).mockReturnValue({ webSessionSecret: '' });
    expect((await POST(request(s.id, 'POST', { token: i.token }), ctx)).status).toBe(503);
});
it('requires an owner browser session to issue and revoke private invitations, and never enrolls on issuance', async () => {
    const { s, i } = prepared();
    const endpoint = 'http://localhost/api/echo/research/invitations';
    const input = { id: s.id, requestId: 'managed', protocolHash: s.protocolHash, expiresAt: new Date(Date.now() + 86400000).toISOString() };
    expect((await issueInvitation(new NextRequest(endpoint, { method: 'POST', headers: { Authorization: 'Bearer owner-token' }, body: JSON.stringify(input) }))).status).toBe(401);
    const headers = { Cookie: 'mindos-session=owner-session' };
    const made = await issueInvitation(new NextRequest(endpoint, { method: 'POST', headers, body: JSON.stringify(input) }));
    expect(made.status).toBe(200);
    const invitation = (await made.json()).invitation;
    const listing = await listInvitations(new NextRequest(endpoint + '?id=' + s.id, { headers }));
    const listingText = JSON.stringify(await listing.json());
    expect(listingText).not.toContain(invitation.token);
    expect(listingText).not.toContain(i.token);
    const revoked = await revokeInvitation(new NextRequest(endpoint, { method: 'PATCH', headers, body: JSON.stringify({ id: s.id, invitationId: invitation.id }) }));
    expect(revoked.status).toBe(200);
    vi.mocked(verifyJwt).mockResolvedValueOnce(null);
    expect((await listInvitations(new NextRequest(endpoint + '?id=' + s.id, { headers }))).status).toBe(401);
});
it('runs scoped assistance exactly once, then permits transfer without returning the conversation', async () => {
    const { executeStudyCoaching } = await import('@/lib/study-coaching-executor');
    const executor = vi.mocked(executeStudyCoaching);
    executor.mockResolvedValue({ status: 'succeeded', output: 'SAVED MODEL HELP', reportedModel: 'fixture-model' });
    let protocol = blankStudyProtocol('en');
    for (const field of studyFields(protocol, 'en')) protocol = changeDraft(protocol, field.path, 'PRIVATE ' + field.path);
    protocol.execution = { adapter: 'isolated-chat-v1', maxTurns: 2 };
    for (const c of protocol.conditions) c.expectedRuntime.endpoint = 'http://localhost:9876/v1/chat/completions';
    const draft = createStudy(testMindRoot, { requestId: 'coaching-api', protocol });
    const s = freezeStudy(testMindRoot, draft.id, { version: draft.version, confirmed: true, reviewedBy: 'owner', reviewNote: 'QA' });
    const i = issueStudyInvitation(testMindRoot, s.id, { requestId: 'coaching-invite', protocolHash: s.protocolHash, expiresAt: new Date(Date.now() + 86400000).toISOString() });
    const ownerResponse = await issueInvitation(new NextRequest('http://localhost/api/echo/research/invitations', { method: 'POST', headers: { Cookie: 'mindos-session=owner-session' }, body: JSON.stringify({ id: s.id, requestId: 'unconfigured-invite', protocolHash: s.protocolHash, expiresAt: new Date(Date.now() + 86400000).toISOString() }) }));
    expect(ownerResponse.status).toBe(503); expect(await ownerResponse.json()).toEqual({ code: 'configuration' });
    const ctx = { params: Promise.resolve({ id: s.id }) };
    const session = await POST(request(s.id, 'POST', { token: i.token }), ctx);
    const cookie = session.headers.get('set-cookie')!.split(';')[0];
    const read = async () => (await (await GET(request(s.id, 'GET', undefined, cookie), ctx)).json()).view.participant;
    const action = async (input: object) => PATCH(request(s.id, 'PATCH', { ...input, version: (await read())?.version }, cookie), ctx);
    await PATCH(request(s.id, 'PATCH', { action: 'join', protocolHash: s.protocolHash, consentAccepted: true }, cookie), ctx);
    await action({ action: 'open' });
    await action({ action: 'answer', answer: 'BASELINE ANSWER', confidence: 50, assistance: 'none', familiar: false });
    expect((await action({ action: 'open' })).status).toBe(200);
    expect((await action({ action: 'answer', answer: 'No help yet', confidence: null, assistance: 'agent', familiar: false })).status).toBe(409);
    const command = { action: 'help', version: (await read()).version, requestId: 'help-one', question: 'Compare explanations?' };
    expect((await PATCH(request(s.id, 'PATCH', command), ctx)).status).toBe(401);
    const reply = await PATCH(request(s.id, 'PATCH', command, cookie), ctx);
    expect(reply.status).toBe(200); expect(JSON.stringify(await reply.json())).toContain('SAVED MODEL HELP');
    expect((await PATCH(request(s.id, 'PATCH', command, cookie), ctx)).status).toBe(200);
    expect(executor).toHaveBeenCalledTimes(1);
    expect(JSON.stringify(executor.mock.calls[0][0])).not.toMatch(/BASELINE ANSWER|reference|tasks.2|tasks.3|rubric/);
    const transfer = await action({ action: 'answer', answer: 'After help', confidence: 60, assistance: 'agent', familiar: false });
    const view = (await transfer.json()).view;
    expect(view.participant.nextPhase).toBe('transfer'); expect(JSON.stringify(view)).not.toContain('SAVED MODEL HELP');
    expect((await action({ action: 'help', requestId: 'late-help', question: 'Not during transfer' })).status).toBe(409);
});
