import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import { beforeEach, afterEach, it, expect, vi } from 'vitest';
import { NextRequest } from 'next/server';
import { createStudy, freezeStudy, enrollStudy, updateStudyParticipant, issueStudyInvitation } from '@geminilight/mindos/knowledge';
import { GET, PATCH } from '@/app/api/study/review/[id]/route';
import { POST } from '@/app/api/study/review/[id]/session/route';
import { GET as list, POST as issue, PATCH as revoke } from '@/app/api/echo/research/reviewers/route';
import { POST as participantSession } from '@/app/api/study/participate/[id]/session/route';
import { readRuntimeAuthConfig } from '@/lib/runtime-auth-config';
import { blankStudyProtocol, studyFields, changeDraft } from '@/components/echo/research/study-draft';
import { testMindRoot } from '../setup';
vi.mock('@/lib/runtime-auth-config', () => ({ readRuntimeAuthConfig: vi.fn(() => ({ authToken: 'owner-token', webPassword: 'password', webSessionSecret: 'session-secret' })) }));
vi.mock('@/lib/jwt', () => ({ verifyJwt: vi.fn(async () => ({ exp: 9999999999 })) }));
let home: string;
beforeEach(() => { home = fs.mkdtempSync(path.join(os.tmpdir(), 'reviewer-api-')); vi.spyOn(os, 'homedir').mockReturnValue(home); });
afterEach(() => { vi.restoreAllMocks(); fs.rmSync(home, { recursive: true, force: true }); });
function setup() {
  let protocol = blankStudyProtocol('en'); for (const field of studyFields(protocol, 'en')) protocol = changeDraft(protocol, field.path, 'PRIVATE ' + field.path);
  protocol.tasks.forEach(t => { t.prompt = 'Synthetic task'; t.reference = 'Frozen scoring reference'; });
  const d = createStudy(testMindRoot, { requestId: 'reviewer-api', protocol });
  const s = freezeStudy(testMindRoot, d.id, { version: d.version, confirmed: true, reviewedBy: 'owner', reviewNote: 'Synthetic' });
  let p = enrollStudy(testMindRoot, s.id, { enrollmentKey: 'participant', protocolHash: s.protocolHash, consentAccepted: true });
  p = updateStudyParticipant(testMindRoot, s.id, p.id, { action: 'open', version: p.version });
  p = updateStudyParticipant(testMindRoot, s.id, p.id, { action: 'answer', version: p.version, answer: 'Synthetic answer', confidence: 70, assistance: 'none', familiar: false });
  return { s, p, ctx: { params: Promise.resolve({ id: s.id }) } };
}
const request = (url: string, method = 'GET', data?: unknown, cookie = '', headers: Record<string, string> = {}) => new NextRequest('http://localhost' + url, { method, headers: { Cookie: cookie, ...headers }, ...(data ? { body: JSON.stringify(data) } : {}) });
const management = '/api/echo/research/reviewers';
it('requires the owner to issue a fixed packet and separates reviewer and participant credentials', async () => {
  const { s, ctx } = setup(); const input = { id: s.id, requestId: 'reviewer-one', label: 'OWNER NOTE', protocolHash: s.protocolHash, expiresAt: new Date(Date.now() + 86400000).toISOString() };
  expect((await issue(request(management, 'POST', input, '', { Authorization: 'Bearer owner-token' }))).status).toBe(401);
  const issued = await issue(request(management, 'POST', input, 'mindos-session=owner')); expect(issued.status).toBe(200);
  const grant = (await issued.json()).invitation; const base = '/api/study/review/' + s.id;
  expect((await GET(request(base), ctx)).status).toBe(401);
  expect((await participantSession(request(base, 'POST', { token: grant.token }), ctx)).status).toBe(401);
  const participant = issueStudyInvitation(testMindRoot, s.id, { requestId: 'participant', protocolHash: s.protocolHash, expiresAt: input.expiresAt });
  expect((await POST(request(base, 'POST', { token: participant.token }), ctx)).status).toBe(401);
  const session = await POST(request(base, 'POST', { token: grant.token }), ctx);
  const setCookie = session.headers.get('set-cookie')!; expect(setCookie).toContain('HttpOnly'); expect(setCookie).toContain('SameSite=strict'); expect(setCookie).toContain('Path=' + base);
  const cookie = setCookie.split(';')[0];
  expect(JSON.stringify(await session.json())).not.toMatch(/OWNER NOTE|Synthetic answer|Frozen scoring|PRIVATE/);
  const accepted = await PATCH(request(base, 'PATCH', { action: 'accept', accepted: true, protocolHash: s.protocolHash }, cookie), ctx); const view = (await accepted.json()).view;
  expect(view.kind).toBe('workspace'); expect(view.items).toHaveLength(1);
  const command = { action: 'rate', requestId: 'rating-one', itemId: view.items[0].id, version: 0, scores: { 'criterion-a': 2 }, rationale: 'Synthetic evaluation.' };
  expect((await PATCH(request(base, 'PATCH', { ...command, reviewerId: 'someone-else' }, cookie), ctx)).status).toBe(400);
  for (let i = 0; i < 2; i++) expect((await PATCH(request(base, 'PATCH', command, cookie), ctx)).status).toBe(200);
  const saved = await GET(request(base, 'GET', undefined, cookie), ctx); expect(saved.headers.get('cache-control')).toContain('no-store'); expect((await saved.json()).view.assessments).toHaveLength(1);
  expect((await PATCH(request(base, 'PATCH', command, cookie, { Origin: 'https://elsewhere.example' }), ctx)).status).toBe(403);
  const listed = await list(request(management + '?id=' + s.id, 'GET', undefined, 'mindos-session=owner')); expect(JSON.stringify(await listed.json())).not.toContain(grant.token);
  await revoke(request(management, 'PATCH', { id: s.id, invitationId: grant.id }, 'mindos-session=owner'));
  expect((await GET(request(base, 'GET', undefined, cookie), ctx)).status).toBe(401);
  const denied = await POST(request(base, 'POST', { token: grant.token }, cookie), ctx); expect(denied.headers.get('set-cookie')).toContain('Max-Age=0');
});
it('keeps unprotected deployments and role-injected exchange requests unavailable', async () => {
  const { s, ctx } = setup(); const base = '/api/study/review/' + s.id;
  expect((await POST(request(base, 'POST', { token: 'x'.repeat(43), role: 'owner' }), ctx)).status).toBe(401);
  vi.mocked(readRuntimeAuthConfig).mockReturnValueOnce({ webSessionSecret: '' });
  expect((await GET(request(base), ctx)).status).toBe(503);
});
it('downloads study records only for the owner, without invitation credentials or reviewer notes', async () => {
  const { s, ctx } = setup();
  const input = { id: s.id, requestId: 'export-reviewer', label: 'PRIVATE_OWNER_NOTE', protocolHash: s.protocolHash, expiresAt: new Date(Date.now() + 86400000).toISOString() };
  const grant = (await (await issue(request(management, 'POST', input, 'mindos-session=owner'))).json()).invitation;
  const { GET: download } = await import('@/app/api/echo/research/export/route');
  const url = '/api/echo/research/export?id=' + s.id;
  expect((await download(request(url, 'GET', undefined, '', { Authorization: 'Bearer owner-token' }))).status).toBe(401);
  const session = await POST(request('/api/study/review/' + s.id, 'POST', { token: grant.token }), ctx);
  expect((await download(request(url, 'GET', undefined, session.headers.get('set-cookie')!.split(';')[0]))).status).toBe(401);
  const exported = await download(request(url, 'GET', undefined, 'mindos-session=owner'));
  expect(exported.status).toBe(200); expect(exported.headers.get('content-disposition')).toContain('attachment'); expect(exported.headers.get('cache-control')).toBe('no-store');
  const text = await exported.text(); expect(text).toContain('Synthetic answer'); expect(text).not.toContain(grant.token); expect(text).not.toContain('PRIVATE_OWNER_NOTE'); expect(text).not.toContain('tokenHash');
  expect((await download(request('/api/echo/research/export?id=invalid', 'GET', undefined, 'mindos-session=owner'))).status).toBe(400);
});
