export const inquiryCopy = {
  en: {
    missingDecision: 'This decision could not be found. The rest of the saved question is available below.',
    linkedMethods: 'Methods under examination',
    linkMethod: 'Link an existing method',
    saveLink: 'Save method link',
    methodSelection: 'Choose an approved method',
    noMethods: 'No eligible approved method. Review a method in Growth first.',
    methodLoadError: 'Could not load methods. Your question is still saved.',
    methodHint:
      'Linking keeps an approved version for comparison. Select it explicitly in a new test to use it. Earlier tests remain unchanged.',
    methodLinkId: 'Method for this test',
    noMethod: 'No linked method attached',
    pausedMethod: 'Paused · may be revised, cannot run',
    activeMethod: 'Available for a test',
    approvedVersion: 'Approved version',
    reviseMethod: 'Revise a linked method',
    revisionTarget: 'Method to revise',
    revisionHint:
      'Describe the changed behavior and why the evidence warrants it. This creates a pending version for human review.',
    saveRevision: 'Save pending revision',
    pendingRevision: 'Revision proposed',
    title: 'Questions worth keeping open',
    lead: 'Keep competing explanations, test what separates them, and leave a trace of how your thinking changes.',
    back: 'Back to growth',
    source: 'Original question and reply',
    private:
      'Saved privately. These records are not automatically added to shared knowledge.',
    empty:
      'Start from a completed conversation. Use “Explore another explanation” beside a reply to keep its source with your question.',
    capture: 'Explore another explanation',
    loading: 'Loading questions…',
    busy: 'Saving…',
    reload: 'Reload',
    retry: 'Retry saved request',
    discard: 'Discard local edits and reload',
    leave: 'You have unsaved edits or a pending request. Leave this page?',
    save: 'Save draft',
    commit: 'Commit my framing',
    revise: 'Revise my framing',
    frameTitle: 'Your framing',
    frameHint:
      'You have already seen the original reply. Write your own judgment before requesting a new challenge. Incomplete drafts can be saved.',
    question: 'Question',
    explanationA: 'Explanation A',
    explanationB: 'Explanation B',
    distinction: 'What evidence would distinguish them?',
    capability: 'What do you want to learn to do?',
    committed: 'Saved framing',
    challenge: 'Prepare a challenge',
    prepared:
      'Review and send the prepared task in the new conversation. Normal conversation context still applies. Keep the task unchanged so its actual run can be matched here.',
    planTitle: 'Design a test',
    planHint:
      'Save the criteria before running the task. The prepared task includes the task, scope and budget; your assessment criteria stay here.',
    task: 'Task to execute',
    supportsA: 'What would support A?',
    supportsB: 'What would support B?',
    inconclusive: 'What would leave the result inconclusive?',
    scope: 'Scope and limits',
    budget: 'Time or resource budget',
    savePlan: 'Save test plan',
    test: 'Prepare this test',
    runs: 'Actual runs',
    readRuns: 'Read and save matching runs',
    noRuns: 'No matching run yet. Preparing a task does not execute it.',
    observe: 'Record an observation',
    observationHint:
      'A quoted Agent output is evidence of what it returned, not proof that a real-world claim is true. Describe the limits in your interpretation.',
    kind: 'Observation source',
    manual: 'My own observation',
    actual: 'Completed matching run',
    choose: 'Choose…',
    sourceLabel: 'Where did you observe this?',
    quote: 'Exact observation or output quote',
    interpretation: 'Your interpretation and limits',
    outcome: 'What does it support?',
    a: 'Explanation A',
    b: 'Explanation B',
    neither: 'Neither explanation',
    uncertain: 'Still uncertain',
    saveObservation: 'Save observation',
    decision: 'Record a decision',
    reason: 'Why this decision?',
    nextQuestion: 'Reframed question',
    evidence: 'Observations supporting this decision',
    noEvidence: 'No observations for this framing. You can keep it open.',
    'keep-a': 'Keep A provisionally',
    'keep-b': 'Keep B provisionally',
    reframe: 'Reframe the question',
    open: 'Keep the question open',
    saveDecision: 'Save decision',
    loadError:
      'Could not read this question. Try reloading when the connection is available.',
    saveFirst: 'Save your edits before committing this framing.',
    fromFrame: 'Revise from this framing',
    history: 'Thinking history',
    proposal: 'Turn this decision into a method proposal',
    behavior: 'What should the Agent do?',
    check: 'How will you check its behavior?',
    saveMethod: 'Save method proposal',
    review: 'Review method proposal',
    close: 'Close form',
    archive: 'Archive question',
    restore: 'Restore question',
    archived: 'Archived',
    saved: 'Saved',
    unavailable:
      'Some records could not be read. Their original files have been preserved.',
    runStates: {
      queued: 'Queued',
      running: 'Running',
      streaming: 'Receiving output',
      waiting_approval: 'Waiting for approval',
      completed: 'Returned',
      failed: 'Failed',
      canceled: 'Canceled',
      timed_out: 'Timed out',
    },
    errors: {
      conflict:
        'The source or record has changed. Your input is still here. Reload deliberately to review the latest version.',
      invalid:
        'Check the required fields, distinct explanations and evidence selection.',
      'not-found': 'This question or its source is unavailable.',
      storage:
        'Could not finish this request. Your input is still here; retry the saved request when ready.',
    },
  },
  zh: {
    missingDecision: '暂时找不到这次决定。下方仍可查看这个问题的其他已保存记录。',
    linkedMethods: '正在检验的方法',
    linkMethod: '关联已有方法',
    saveLink: '保存方法关联',
    methodSelection: '选择已批准的方法',
    noMethods: '暂无可关联的已批准方法，请先到成长页审阅方法。',
    methodLoadError: '未能读取方法，问题记录仍已保存。',
    methodHint:
      '关联会保留已批准版本用于对照。在新的检验方案中明确选择它，才会附带使用；此前的检验保持原样。',
    methodLinkId: '本次检验使用的方法',
    noMethod: '不附带关联方法',
    pausedMethod: '已暂停 · 可提出修订，不能运行',
    activeMethod: '可用于检验',
    approvedVersion: '已批准版本',
    reviseMethod: '修订关联的方法',
    revisionTarget: '要修订的方法',
    revisionHint:
      '说明行为需要如何改变，以及证据为何支持修改。保存后形成待审版本，需要人工审阅。',
    saveRevision: '保存待审修订',
    pendingRevision: '已提出修订',
    title: '值得继续追问的问题',
    lead: '保留不同解释，检验它们的分歧，记录自己的想法如何改变。',
    back: '返回成长',
    source: '最初的问题与回答',
    private: '记录私密保存，不会自动加入共享知识。',
    empty:
      '从一次已完成的对话开始。点击回答旁的“保留另一种解释”，把问题和原始出处一起保存。',
    capture: '保留另一种解释',
    loading: '正在读取问题…',
    busy: '正在保存…',
    reload: '重新读取',
    retry: '重试上次请求',
    discard: '放弃本地修改并重新读取',
    leave: '有尚未保存的修改或待确认的请求，仍然离开此页？',
    save: '保存草稿',
    commit: '提交我的判断',
    revise: '修订我的判断',
    frameTitle: '你的判断',
    frameHint:
      '你已经看过原始回答。先写下自己的判断，再请求新的挑战；没有写完也可以保存草稿。',
    question: '问题',
    explanationA: '解释 A',
    explanationB: '解释 B',
    distinction: '什么证据能区分它们？',
    capability: '你希望学会什么？',
    committed: '已保存的判断',
    challenge: '准备一次挑战',
    prepared:
      '请在新对话中审阅并发送准备好的任务，普通对话上下文仍会生效。保留任务原文，才能在这里匹配实际运行。',
    planTitle: '设计一次检验',
    planHint:
      '先保存判据，再运行任务。准备的任务包含任务、范围和预算，你的判断标准保留在这里。',
    task: '要执行的任务',
    supportsA: '什么结果支持 A？',
    supportsB: '什么结果支持 B？',
    inconclusive: '什么情况仍无法判断？',
    scope: '适用范围与限制',
    budget: '时间或资源预算',
    savePlan: '保存检验方案',
    test: '准备这次检验',
    runs: '实际运行',
    readRuns: '读取并保存匹配的运行',
    noRuns: '还没有匹配的运行。准备任务并不代表已经执行。',
    observe: '记录一条观察',
    observationHint:
      'Agent 输出的引文只能说明它返回了什么，不能直接证明现实中的主张成立。请在解释中注明局限。',
    kind: '观察来源',
    manual: '我自己的观察',
    actual: '已完成的匹配运行',
    choose: '请选择…',
    sourceLabel: '你在哪里观察到？',
    quote: '实际观察或输出原文',
    interpretation: '你的解释与局限',
    outcome: '它支持什么？',
    a: '解释 A',
    b: '解释 B',
    neither: '两种解释都不支持',
    uncertain: '仍不确定',
    saveObservation: '保存观察',
    decision: '记录一次决定',
    reason: '为什么这样决定？',
    nextQuestion: '重新提出的问题',
    evidence: '支持这次决定的观察',
    noEvidence: '这一版判断还没有观察，可以先保持开放。',
    'keep-a': '暂时保留 A',
    'keep-b': '暂时保留 B',
    reframe: '重新提出问题',
    open: '保持问题开放',
    saveDecision: '保存决定',
    loadError: '暂时无法读取问题，连接恢复后可以重新读取。',
    saveFirst: '请先保存修改，再提交这一版判断。',
    fromFrame: '从这一版继续修订',
    history: '思考历程',
    proposal: '把这次决定整理为方法提案',
    behavior: 'Agent 应该怎么做？',
    check: '如何检查它的行为？',
    saveMethod: '保存方法提案',
    review: '审阅方法提案',
    close: '收起表单',
    archive: '归档问题',
    restore: '恢复问题',
    archived: '已归档',
    saved: '已保存',
    unavailable: '部分记录无法读取，原始文件已保留。',
    runStates: {
      queued: '等待执行',
      running: '运行中',
      streaming: '正在接收输出',
      waiting_approval: '等待批准',
      completed: '已返回',
      failed: '失败',
      canceled: '已取消',
      timed_out: '已超时',
    },
    errors: {
      conflict:
        '出处或记录已有变化，你的输入仍在。请主动重新读取，再核对最新版本。',
      invalid: '请检查必填项、两种解释的区别及证据选择。',
      'not-found': '问题或原始出处暂时无法读取。',
      storage: '这次请求未能完成，输入仍在。准备好后可以重试上次请求。',
    },
  },
};
export type InquiryCopy = typeof inquiryCopy.en | typeof inquiryCopy.zh;
