export { ACP_ERRORS } from '@geminilight/mindos/protocols/acp';
// ACP wire types: one source in the Web package. `@/lib/types` re-exports
// them from `@geminilight/mindos/client-types`; this module only keeps the
// historical import path alive for the ACP adapters and their tests
// (spec-client-types-and-sse-parsers).
export type {
  AcpAdapterConnectionType,
  AcpAgentCapabilities,
  AcpAuthMethod,
  AcpAvailableCommand,
  AcpClientCapabilities,
  AcpConfigOption,
  AcpConfigOptionEntry,
  AcpContentBlock,
  AcpMcpCapabilities,
  AcpMode,
  AcpPermissionEvent,
  AcpPermissionEventStatus,
  AcpPermissionOutcome,
  AcpPermissionOption,
  AcpPlan,
  AcpPlanEntry,
  AcpPlanEntryPriority,
  AcpPlanEntryStatus,
  AcpPromptCapabilities,
  AcpPromptResponse,
  AcpRegistry,
  AcpRegistryEntry,
  AcpSession,
  AcpSessionCapabilities,
  AcpSessionControlSnapshot,
  AcpSessionInfo,
  AcpSessionSnapshot,
  AcpSessionSnapshotFactSource,
  AcpSessionState,
  AcpSessionToolSummary,
  AcpSessionUpdate,
  AcpStopReason,
  AcpToolCall,
  AcpToolCallFull,
  AcpToolCallKind,
  AcpToolCallStatus,
  AcpToolResult,
  AcpTransportType,
  AcpUpdateType,
} from '@/lib/types';
